name: "validation.bulk.static"

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/validation.bulk.static.yml"
      - ".github/actions/templates/avm-**"
      - ".github/workflows/avm.template.module.yml"
      - "utilities/pipelines/**"
      - "!utilities/pipelines/platform/**"
      - "!*/**/README.md"

concurrency:
  group: ${{ github.workflow }}

jobs:
  #############################################
  #   Run static validation for all modules   #
  #############################################
  job_bulk_static:
    runs-on: ubuntu-latest
    name: "Initialize pipeline"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Trigger bulk
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            # Load used functions
            Write-Verbose "Hello bulk"
